planner_client:
  ros__parameters:
    plan_solver_timeout: 60.0
planner:
  ros__parameters:
    plan_solver_timeout: 60.0
    plan_solver_plugins: ["POPF"]
    POPF:
      plugin: "plansys2/POPFPlanSolver"
    OPTIC:
      plugin: "plansys2/OPTICPlanSolver"